config/routes.rb
Rails.application.routes.draw do
  root to: 'notes#home'
  devise_for :users

  resources :notes, except: [:index] do
    collection do
      get :drafted
      get :shared
      get :shared_with_me
    end
    member do
      post :share
      delete :remove_access
    end
  end
end

app/models/note.rb
class Note < ApplicationRecord
  resourcify
  belongs_to :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings, dependent: :destroy
  self.per_page = 10

  validates_presence_of :title, :body

  scope :drafted, -> { where(shared: false) }
  scope :shared, -> { where(shared: true) }
  scope :recently_modified, -> { order('updated_at desc') }

  after_create :assign_owner

  def tags_list=(value)
    value.downcase.split(',').map(&:squish).uniq.each do |tag|
      next unless tag.present?
      tags << Tag.where(name: tag).first_or_create
    end
  end

  def tags_list
    tags.pluck(:name).join(', ')
  end

  def tags_list_numbered
    tags.map { |tag| "#{tag.name}(#{tag.notes_count})" }.join(', ')
  end

  def update_tags(list)
    new_list = list.downcase.split(',').map(&:squish).uniq
    old_list = tags.pluck(:name)
    common_list = new_list & old_list
    save_tags_list(new_list, old_list, common_list)
  end

  def save_tags_list(new_list, old_list, common_list)
    tags = self.tags
    Tag.where(name: (old_list - common_list)).each { |t| tags.delete(t) }
    (new_list - common_list).each { |tag| tags << Tag.where(name: tag).first_or_create }
  end

  def added_role_to_user?(params, provider_id)
    if (user = User.find_by_email(params[:email].downcase)).present? && user_id != user.id
      remove_previous_role_if_any(user, params[:role])
      add_new_role(user, params[:role], provider_id)
      true
    else
      false
    end
  end

  def remove_previous_role_if_any(user, role)
    previus_role = user.roles.where(resource_id: id).first
    return unless previus_role.present?
    user.remove_role(previus_role.name, self) unless previus_role.name.eql?(role)
  end

  def add_new_role(user, role, provider_id)
    role = user.add_role(role, self)
    role.users_roles.where(user_id: user.id).first.update_column(:provider_id, provider_id)
  end

  def remove_role_from_user(user, role)
    user.remove_role(role, self)
    UsersRole.includes(:role).where(provider_id: user.id, 'roles.resource_id' => id).each do |user_role|
      user_role.user.remove_role(user_role.role.name, self)
    end
  end

  private

  def assign_owner
    user.add_role(:owner, self)
  end
end

app/controllers/concerns/notes_helper.rb
module NotesHelper
  def note_shareable?
    params[:commit] == 'Save & Share'
  end

  def owner_text(note)
    name = if current_user.has_role?(:owner, note)
             'You are'
           else
             "#{note.user.name} is"
           end
    "#{name} the owner of this Note."
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  include NotesHelper
  before_action :set_note, only: %i[show edit]
  load_and_authorize_resource
  skip_authorize_resource only: %i[home new create drafted shared shared_with_me]
  before_action :initialize_note, only: %i[new create]
  before_action :set_sharing_status, only: %i[create update]

  def home
    redirect_to drafted_notes_path if current_user.present?
  end

  def create
    @note.assign_attributes(note_params)
    if @note.save
      redirect_to note_path(@note)
    else
      render :new
    end
  end

  def update
    if @note.update_attributes(note_params.except(:tags_list))
      @note.update_tags(note_params[:tags_list])
      redirect_to note_path(@note)
    else
      render :edit
    end
  end

  def drafted
    @notes = current_user.notes.drafted.recently_modified.page(params[:page] || 1)
  end

  def shared
    @notes = current_user.notes.shared.recently_modified.page(params[:page] || 1)
  end

  def share
    msg = if @note.added_role_to_user?(share_params, current_user.id)
            "#{share_params[:email]} successfully added."
          else
            "#{share_params[:email]} could not be added."
          end
    redirect_to note_path(@note), flash: { notice: msg }
  end

  def remove_access
    user = User.find_by_email(params[:email])
    msg = if user.present?
            @note.remove_role_from_user(user, params[:role])
            "#{user.name} has been removed."
          else
            "Couldn't find user"
          end
    redirect_to note_path(@note), flash: { error: msg }
  end

  def destroy
    if @note.destroy
      redirect_to root_path, flash: { error: 'Successfully deleted Note!' }
    else
      redirect_to edit_note_path(@note), flash: { error: 'Error Deleting post!' }
    end
  end

  def shared_with_me
    @notes = Note.includes(:user).with_roles(User::ROLES.except(:owner).keys, current_user)
                 .page(params[:page] || 1)
  end

  private

  def note_params
    params.require(:note).permit(:title, :body, :tags_list, :shared)
  end

  def share_params
    params.require(:share).permit(:email, :role)
  end

  def set_sharing_status
    params[:note][:shared] = note_shareable?
  end

  def initialize_note
    @note = current_user.notes.new
  end

  def set_current_note
    @note = Note.includes(:user).find(params[:id])
  end

  def set_note
    @note = Note.includes(:tags).find(params[:id])
  end
end

app/views/notes/_form.html.haml
.row
  .col-md-8.col-md-offset-2
    = form_for(@note) do |f|
      - if @note.errors.any?
        #error_explanation
          %h2
            = "#{pluralize(@note.errors.count, 'error')} prohibited this note from being saved:"
          %ul
            - @note.errors.full_messages.each do |msg|
              %li
                = msg
      = f.label :title
      = f.text_field :title, autofocus: true, class: 'form-control', required: true
      %br
      = f.label :body
      = f.text_area :body, autocomplete: 'off', rows: 20, class: 'form-control', required: true
      %br
      = f.label :tags_list
      %em
        (Enter comma seperated tags.)
      = f.text_field :tags_list, class: 'form-control'
      %br
      = f.submit 'Save & Share', class: 'btn btn-success'
      - unless @note.shared?
        = f.submit 'Draft', class: 'btn btn-warning'
    %br
    - if can? :destroy, @note
      = form_for(@note, html: { method: :delete }) do |f|
        = f.submit 'Delete', method: 'delete', class: 'btn btn-danger'

app/views/notes/_listing.html.haml
- provide(:title, title)
- notes.each do |note|
  %h2
    %a{href: note_path(note)}= note.title
  .row
    .group1.col-sm-6.col-md-6
      %span.glyphicon.glyphicon-pencil
      = note.user.name
    .group2.col-sm-6.col-md-6{style: 'text-align: right;'}
      %span.glyphicon.glyphicon-calendar
      = note.created_at.strftime('%b %d, %Y')
      %span.glyphicon.glyphicon-share
      = note.share_count
  %hr
  %p.lead{style: 'text-align: justify;'}= truncate(note.body, length: 250)
  %span.glyphicon.glyphicon-tags
    = note.tags_list
  %p.text-right
    %a{href: note_path(note)}
      continue reading...
  %hr

app/views/notes/_shared_users.html.haml
- User::ROLES.map do |k,v|
  - if k.eql?(:owner)
    %h6= owner_text(note)
  - elsif (users = User.with_role(k, note)).present?
    .panel-group
      .panel.panel-default
        %a{'data-toggle' => 'collapse', href: "#user-list-#{k}", style: 'text-decoration:none'}
          .panel-heading
            .panel-title
              = "Following users have #{v} access to this note."
        .panel-collapse.collapse{id: "user-list-#{k}"}
          %ul.list-group
            - users.each do |user|
              %li.list-group-item
                .row{style: 'padding:0px 10px'}
                  = user.name
                  -if can?(:remove_access, note)
                    = link_to "<span class='glyphicon glyphicon-trash'></span>".html_safe, remove_access_note_path(note, email: user.email, role: k), method: :delete, style: 'color:red;float:right'

app/views/notes/drafted.html.haml
%article
  = render partial: 'listing', locals: {notes: @notes, title: 'My Drafts'}
%ul.pager
  = will_paginate @notes, renderer: BootstrapPagination::Rails

app/views/notes/edit.html.haml
- provide(:title, 'Edit Note')
%h1.page-header{align: 'center'} Edit Note
= render partial: 'form'

app/views/notes/home.html.haml
.container
  .row
    .col-md-12
      %div
        = image_tag("home.gif", class: 'imgwrapper img-responsive', style: 'margin:auto;padding:10%;')

app/views/notes/new.html.haml
- provide(:title, 'New Note')
%h1.page-header{align: 'center'} New Note
= render partial: 'form'

app/views/notes/shared.html.haml
%article
  = render partial: 'listing', locals: {notes: @notes, title: 'Shared'}
%ul.pager
  = will_paginate @notes, renderer: BootstrapPagination::Rails

app/views/notes/shared_with_me.html.haml
%article
  = render partial: 'listing', locals: {notes: @notes, title: 'Shared with Me'}
%ul.pager
  = will_paginate @notes, renderer: BootstrapPagination::Rails

app/views/notes/show.html.haml
- provide(:title, @note.title)
.container
  .row
    .col-md-10.col-md-offset-1
      .row
        %article
          %h2= @note.title
          .row
            .group1.col-sm-6.col-md-6
              %span.glyphicon.glyphicon-pencil
              = @note.user.name
            .group2.col-sm-6.col-md-6{style: "text-align: right;"}
              %span.glyphicon.glyphicon-calendar
              = @note.created_at.strftime("%b %d, %Y")
              %span.glyphicon.glyphicon-share
              = @note.share_count
          %hr
          %p.lead{style: "text-align: justify;"}= @note.body
          %span.glyphicon.glyphicon-tags
            = @note.tags_list_numbered
          %hr
          - if can? :update, @note
            = button_to "Edit note", edit_note_path(@note), method: 'get', class: "btn btn-primary"
            %hr
          - if @note.shared? && can?(:share, @note)
            .row
              = form_for(:share, url: share_note_path(@note)) do |f|
                .col-md-6
                  = f.email_field :email, class: 'form-control', required: true, placeholder: "Enter Email.."
                .col-md-4
                  = f.select :role, User::ROLES.except(:owner).map{ |k,v| [v, k] }, {}, class: 'form-control'
                .col-md-2
                  = f.submit "Share", class: 'btn btn-success', style: 'float:right'
          = render partial: 'shared_users', locals: {note: @note}