config/routes.rb
Rails.application.routes.draw do
  root to: 'notes#home'
  devise_for :users

  resources :notes, except: [:index] do
    collection do
      get :drafted
      get :shared
      get :shared_with_me
    end
    member do
      post :share
      delete :remove_access
    end
  end
end

app/views/layouts/_footer.html.haml
.container{style: 'position:fixed;'}
  .navbar.navbar-inverse.navbar-fixed-bottom{role: 'navigation'}
    .row
      .group1.col-md-8.col-md-offset-2{style: 'text-align: center;'}
        %a{href: 'https://github.com/md-farhan-memon/note_me', target: '_blank', title: 'GitHub - NoteMe'}
          %img{src: '/gh.png'}
        %a{href: 'https://in.linkedin.com/in/mdfarhanmemon', target: '_blank', title: 'LinkedIn Profile'}
          %img{src: '/li.png'}
        %a{href: 'https://www.facebook.com/mdfarhan.memon', target: '_blank', title: 'Facebook Profile'}
          %img{src: '/fb.png'}

app/views/layouts/_header.html.haml
%header.navbar.navbar-default.navbar-fixed-top{role: 'navigation'}
  .container
    .row
      .col-md-8.col-md-offset-2
        .navbar-header
          %button.navbar-toggle{'data-target' => '.navbar-collapse', 'data-toggle' => 'collapse', type: 'button'}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: '/'} NoteMe
        .navbar-collapse.collapse
          %ul.nav.navbar-nav.navbar-right
            - if current_user.present?
              %li
                = link_to 'New Note', new_note_path
              %li.dropdown
                %a.dropdown-toggle{'data-toggle' => 'dropdown', href: ''}
                  My Notes
                  %b.caret
                %ul.dropdown-menu
                  %li
                    = link_to 'Drafted Notes', drafted_notes_path
                  %li
                    = link_to 'Shared Notes', shared_notes_path
                  %li
                    = link_to 'Shared with me', shared_with_me_notes_path
                %li.dropdown
                  %a.dropdown-toggle{'data-toggle' => 'dropdown', href: ''}
                    Settings
                    %b.caret
                  %ul.dropdown-menu
                    %li
                      = link_to 'Change Password', edit_user_registration_path
                    %li
                      = link_to 'LogOut', destroy_user_session_path, method: 'delete'
            - else
              %li
                = link_to 'LogIn', new_user_session_path
              %li
                = link_to 'SignUp', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8; width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=0', 'http-equiv' => 'Content-Type', name: 'viewport' }
    %title= full_title(yield(:title))
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body{style: 'padding-top: 70px; padding-bottom: 70px'}
    = render partial: 'layouts/header'
    .container
      - flash.each do |name, msg|
        = content_tag :div, msg, class: 'alert alert-info'
      = yield
    = render partial: 'layouts/footer'